"""initial migration

Revision ID: ba93b0130119
Revises:
Create Date: 2026-06-03 21:18:05.158719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba93b0130119"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("cust_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cust_ref_no", sa.String(length=20), nullable=False),
        sa.Column("f_name", sa.String(length=80), nullable=False),
        sa.Column("l_name", sa.String(length=80), nullable=False),
        sa.Column("cust_seg", sa.String(length=20), nullable=True),
        sa.Column("kyc_stat", sa.String(length=10), nullable=True),
        sa.Column("prim_email", sa.String(length=150), nullable=True),
        sa.Column(
            "created_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cust_id"),
        sa.UniqueConstraint("cust_ref_no"),
        schema="data_service",
    )
    op.create_table(
        "products",
        sa.Column("prod_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prod_cd", sa.String(length=20), nullable=False),
        sa.Column("prod_nm", sa.String(length=100), nullable=False),
        sa.Column("prod_cat", sa.String(length=20), nullable=False),
        sa.Column("prod_sub_cat", sa.String(length=20), nullable=True),
        sa.Column("int_rate_pct", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column(
            "fee_monthly_amt",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=True,
        ),
        sa.Column("ccy_cd", sa.CHAR(length=3), server_default="GBP", nullable=True),
        sa.Column("is_avail_flg", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("prod_id"),
        sa.UniqueConstraint("prod_cd"),
        schema="data_service",
    )
    op.create_table(
        "txn_cat_ref",
        sa.Column("cat_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cat_cd", sa.String(length=15), nullable=False),
        sa.Column("cat_desc", sa.String(length=100), nullable=True),
        sa.Column("is_debit_flg", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("cat_id"),
        sa.UniqueConstraint("cat_cd"),
        schema="data_service",
    )
    op.create_table(
        "acct_info",
        sa.Column("acct_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("acct_no", sa.String(length=20), nullable=False),
        sa.Column("prod_id", sa.Integer(), nullable=False),
        sa.Column(
            "acct_stat", sa.String(length=10), server_default="ACTIVE", nullable=False
        ),
        sa.Column("open_dt", sa.Date(), nullable=False),
        sa.Column(
            "curr_bal_amt",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "avail_bal_amt",
            sa.Numeric(precision=18, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "od_limit_amt",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=True,
        ),
        sa.Column("ccy_cd", sa.CHAR(length=3), server_default="GBP", nullable=False),
        sa.Column("last_txn_dt", sa.Date(), nullable=True),
        sa.Column(
            "created_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["data_service.products.prod_id"],
        ),
        sa.PrimaryKeyConstraint("acct_id"),
        sa.UniqueConstraint("acct_no"),
        schema="data_service",
    )
    op.create_table(
        "acct_prod_map",
        sa.Column("map_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("acct_id", sa.Integer(), nullable=False),
        sa.Column("prod_id", sa.Integer(), nullable=False),
        sa.Column(
            "enrol_dt",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column(
            "prov_status", sa.String(length=10), server_default="ACTIVE", nullable=True
        ),
        sa.Column("note_txt", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acct_id"],
            ["data_service.acct_info.acct_id"],
        ),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["data_service.products.prod_id"],
        ),
        sa.PrimaryKeyConstraint("map_id"),
        sa.UniqueConstraint("acct_id", "prod_id", name="uq_acct_prod"),
        schema="data_service",
    )
    op.create_table(
        "cust_acct_map",
        sa.Column("map_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cust_id", sa.Integer(), nullable=False),
        sa.Column("acct_id", sa.Integer(), nullable=False),
        sa.Column(
            "rel_typ", sa.String(length=20), server_default="PRIMARY", nullable=False
        ),
        sa.Column(
            "eff_from_dt",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("eff_to_dt", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acct_id"],
            ["data_service.acct_info.acct_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cust_id"],
            ["data_service.customer.cust_id"],
        ),
        sa.PrimaryKeyConstraint("map_id"),
        sa.UniqueConstraint("cust_id", "acct_id", "rel_typ", name="uq_cust_acct_rel"),
        schema="data_service",
    )
    op.create_table(
        "transactions_ledger",
        sa.Column("txn_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("txn_ref", sa.String(length=30), nullable=False),
        sa.Column("acct_id", sa.Integer(), nullable=False),
        sa.Column("cat_id", sa.Integer(), nullable=True),
        sa.Column("txn_typ", sa.String(length=10), nullable=False),
        sa.Column("txn_dt", sa.Date(), nullable=False),
        sa.Column("amt", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("ccy_cd", sa.CHAR(length=3), server_default="GBP", nullable=False),
        sa.Column("bal_after_amt", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("chan_cd", sa.String(length=10), nullable=True),
        sa.Column("narr_txt", sa.String(length=255), nullable=True),
        sa.Column(
            "created_ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amt > 0", name="chk_txn_amt_positive"),
        sa.ForeignKeyConstraint(
            ["acct_id"],
            ["data_service.acct_info.acct_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cat_id"],
            ["data_service.txn_cat_ref.cat_id"],
        ),
        sa.PrimaryKeyConstraint("txn_id"),
        sa.UniqueConstraint("txn_ref"),
        schema="data_service",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions_ledger", schema="data_service")
    op.drop_table("cust_acct_map", schema="data_service")
    op.drop_table("acct_prod_map", schema="data_service")
    op.drop_table("acct_info", schema="data_service")
    op.drop_table("txn_cat_ref", schema="data_service")
    op.drop_table("products", schema="data_service")
    op.drop_table("customer", schema="data_service")
    # ### end Alembic commands ###
